name: 'Varning för Villeroy & Boch'
favicon: null
layout_spectrum: 0.76066
typography_spectrum: 0.4620456483680755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b4d1f9'
    - '#e0de55'
    - '#222126'
    - '#d99aad'
  brandStrength: 0.625
  lightness: 0.24810989946126938
  saturation: 0.5628516701981425
  rhythmicContrast: 0.2709314674139023
purpose: []
